### ISSUE TITLE
[Feature request] React to bomb explosion

### ISSUE THREAD

**Issue by almondlynx** [purrplingcat/NpcAdventures#118]
I am a devoted demolitionist. In lategame I don't even mine anymore - I commit megabomb skullcavern descents with my husband for quick iridium. But when I bomb he doesn't seem bothered. At all.
I would like for NPC's to jump and/or emote or say something on bomb explosion nearby. That will liven up othervise stale skullcavern speedruns.

**Comment by purrplingcat** [comment]
Hi, thank you for your suggestions, sounds nice.

I can react only with reaction like jump, scared shake (like Abigail's react in mines when bat flying out), but I can't do NPC damage (NPCs in vanilla hasn't stamina and health). 

Currently our priorities is not implement suggestions in current beta phase, we are focused to issueds from Phase 2 on roadmap and for requirements from our content artist. I'll implement it in future. If you want it in next versions soon and you are developer, you can try to implement it and send me PR. Otherwise be patient and wait until we can add it to development.

I add it to roadmap to "future phase" column.

**Comment by purrplingcat** [comment]
I got an additional idea for this effect. When bomb explodes and the explosion intersects with companion NPC, a friendship will decrease when NPC emotes or "scare shake" or jump.

It's a -20 friendship points loss balanced?

**Comment by almondlynx** [comment]
It would be better to set friendship damage value at 10 every morning and add 10 each time character gets bombed up(second time it's 20 damage, third 30 and after fourth time damage hits it's cap at 50). Dates and spouses should have less than 10, though, for example, 8 and 5 respectively.
This will be a slightly more versatile solution that takes different kinds of players into account.

**Comment by purrplingcat** [comment]
```
int bombedCounter = 0

event onNpcBombedUp => NPC.friendship -= ++bombedCounter * 10

event onDayStarted => bombedCounter = 0
```

**Comment by almondlynx** [comment]
Yes, nice enough

**Comment by purrplingcat** [comment]
Discontinued
